name: "Dokku Deployment"
description: "Deploys your project to dokku."
branding:
  icon: "upload-cloud"
  color: purple
inputs:
  dokku-deploy-key:
    description: "SSH private key to dokku instance."
    required: true
  dokku-host:
    description: "Dokku host."
    required: true
  dokku-app:
    description: "Application name on dokku."
    required: true
  dokku-user:
    description: "Username for dokku host."
    required: false
    default: "dokku"
  force-push:
    description: "Forces git push command with --force flag. | default: false"
    required: false
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dokku-deploy-key }}
    - ${{ inputs.dokku-host }}
    - ${{ inputs.dokku-app }}
    - ${{ inputs.dokku-user }}
    - ${{ inputs.force-push }}
